context:
  version: "0.0.33"

package:
  name: genai-prices
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/g/genai-prices/genai_prices-${{ version }}.tar.gz
    sha256: 61d8ac7da4c72ad1eeefef03ab0c1fbb17b9af5e54107d8dda471ba0b7546daa
  - url: https://raw.githubusercontent.com/pydantic/genai-prices/v${{ version }}/LICENSE
    sha256: ab47bf0bbd619cd73e16fd7873c7e0798e7aa62bcc9ae2fc79cbcb9799e609f6

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - genai-prices = genai_prices._cli:cli
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build >=0.8.8
    - pip
  run:
    - python >=${{ python_min }}
    - eval-type-backport >=0.2
    - httpx >=0.28.1
    - pydantic >=2.11.7

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - genai_prices
      pip_check: true

about:
  summary: Calculate prices for calling LLM inference APIs.
  homepage: https://github.com/pydantic/genai-prices
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
