context:
  version: "0.1.7"

package:
  name: genai-prices
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/g/genai-prices/genai_prices-${{ version }}.tar.gz
    sha256: 4305395c5891796860c697cc3a49ab50b751ed62c8ff1911e291ea8da77f3a91
  - url: https://raw.githubusercontent.com/pydantic/genai-prices/v${{ version }}/LICENSE
    sha256: ab47bf0bbd619cd73e16fd7873c7e0798e7aa62bcc9ae2fc79cbcb9799e609f6

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - genai-prices = genai_prices._cli:cli
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning >=0.7.0
    - pip
  run:
    - python >=${{ python_min }}
    - httpx2 >=2.0
    - pydantic >=2.10
    - pydantic-settings >=2.11
    - rich >=14.3.2
    - rich-argparse >=1.7.2

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - genai_prices
      pip_check: true

about:
  summary: Calculate prices for calling LLM inference APIs.
  homepage: https://github.com/pydantic/genai-prices
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
